### ISSUE TITLE
If no know last page how much

### ISSUE THREAD

**Issue by hafiz013** [Ahmad-Hamwi/lazy-pagination-compose#1]
I have seen this code need last page, may i know if let say i didn't how much page total is? it possible

**Comment by Ahmad-Hamwi** [comment]
Hello, You're data source should tell you if you've reached the last page.
If it didn't provide you with such information, you either need to figure out when it's going to be the last page or unfortunately keep infinitely scrolling.

**Comment by Ahmad-Hamwi** [comment]
Since this isn't an issue with the library, I'll be closing this issue. Let me know if you need any further help.
