### ISSUE TITLE
Question: Are there any way to refresh without reset pagination state?

### ISSUE THREAD

**Issue by Moozart** [Ahmad-Hamwi/lazy-pagination-compose#6]
When I use refresh after turn back to my Screen(voyager) I am calling refresh but scroll position reset even I use paginationState.refresh(viewmodel.state.lastCurrentIndex). Are there any way to use only update data of current page

**Comment by Ahmad-Hamwi** [comment]
Hello, check out the new function available in [1.3.7](https://github.com/Ahmad-Hamwi/lazy-pagination-compose/releases/tag/v1.3.7)

`appendPageWithUpdates(...)` function allows you to modify the items list when you add a page.
